services:

  App\Services\AccountService:
      class:     App\Services\AccountService

  App\Services\AccountBetaService:
      class:     App\Services\AccountBetaService

  App\Services\BankService:
      class:     App\Services\BankService
      arguments:
          - '@App\Services\AccountBetaService'
